/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/**
 *
 * @author Rolivis
 */
public class JFrameInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form JFrameInterfaz
     */
    int mousex, mousey;
    public JFrameInterfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
     public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Bayern.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelnombreCarro = new javax.swing.JLabel();
        jLabelNumeroCarro = new javax.swing.JLabel();
        nombrecarro = new javax.swing.JTextField();
        numerocarro = new javax.swing.JFormattedTextField();
        aniadircarro = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroNegro.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 30, 30));

        jLabelnombreCarro.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelnombreCarro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelnombreCarro.setText("Nombre de carro:");
        getContentPane().add(jLabelnombreCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jLabelNumeroCarro.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelNumeroCarro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroCarro.setText("Numero del carro:");
        getContentPane().add(jLabelNumeroCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, -1, -1));

        nombrecarro.setBackground(new java.awt.Color(0, 0, 0));
        nombrecarro.setForeground(new java.awt.Color(255, 255, 255));
        nombrecarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrecarroActionPerformed(evt);
            }
        });
        getContentPane().add(nombrecarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 470, 40));

        numerocarro.setBackground(new java.awt.Color(0, 0, 0));
        numerocarro.setForeground(new java.awt.Color(255, 255, 255));
        numerocarro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("####"))));
        numerocarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerocarroActionPerformed(evt);
            }
        });
        getContentPane().add(numerocarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 470, 40));

        aniadircarro.setBackground(new java.awt.Color(153, 153, 153));
        aniadircarro.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 18)); // NOI18N
        aniadircarro.setForeground(new java.awt.Color(255, 255, 255));
        aniadircarro.setText("Ingresar nuevo carro");
        aniadircarro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aniadircarroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aniadircarroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aniadircarroMouseExited(evt);
            }
        });
        getContentPane().add(aniadircarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 240, 50));

        jPanel1.setBackground(new java.awt.Color(101, 5, 5));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo Rojo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1001, 617));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nombrecarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrecarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrecarroActionPerformed

    private void numerocarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerocarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerocarroActionPerformed

    private void aniadircarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aniadircarroMouseClicked
        // TODO add your handling code here:
        if(nombrecarro.getText().equalsIgnoreCase("")||numerocarro.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Falto uno o dos datos, no se aniadio el carro");
        }else{
            JOptionPane.showMessageDialog(null, "Se ingreso un carro correctamente");
        }
    }//GEN-LAST:event_aniadircarroMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mousex = evt.getX();
        mousey = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mousex, y - mousey);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void aniadircarroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aniadircarroMouseEntered
        aniadircarro.setBackground(Color.white);
        aniadircarro.setForeground(Color.black);
    }//GEN-LAST:event_aniadircarroMouseEntered

    private void aniadircarroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aniadircarroMouseExited
        aniadircarro.setBackground(Color.GRAY);
        aniadircarro.setForeground(Color.white);
    }//GEN-LAST:event_aniadircarroMouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setBackground(Color.white);
        jButton1.setForeground(Color.red);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(Color.black);
        jButton1.setForeground(Color.white);
    }//GEN-LAST:event_jButton1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aniadircarro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNumeroCarro;
    private javax.swing.JLabel jLabelnombreCarro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombrecarro;
    private javax.swing.JFormattedTextField numerocarro;
    // End of variables declaration//GEN-END:variables
}
